# Health Check
GET https://be-123230219-dot-kelas-if-b-kelompok-16.et.r.appspot.com/ HTTP/1.1

###
# GET all notes
GET https://be-123230219-dot-kelas-if-b-kelompok-16.et.r.appspot.com/api/v1/notes HTTP/1.1
Content-Type: application/json

###
# GET note by id
GET https://be-123230219-dot-kelas-if-b-kelompok-16.et.r.appspot.com/api/v1/notes/1 HTTP/1.1
Content-Type: application/json

###
# POST create note
POST https://be-123230219-dot-kelas-if-b-kelompok-16.et.r.appspot.com/api/v1/notes HTTP/1.1
Content-Type: application/json

{
  "judul": "Belanja Mingguan",
  "isi": "Beli beras, telur, dan sayur di pasar."
}

###
# PUT update note
PUT https://be-123230219-dot-kelas-if-b-kelompok-16.et.r.appspot.com/api/v1/notes/1 HTTP/1.1
Content-Type: application/json

{
  "judul": "Belanja Mingguan Update",
  "isi": "Tambah susu dan buah."
}

###
# DELETE note
DELETE https://be-123230219-dot-kelas-if-b-kelompok-16.et.r.appspot.com/api/v1/notes/1 HTTP/1.1
Content-Type: application/json